import {
  ProgramNode, ASTNode, ExpressionNode, NZSType,
  ConstDeclaration, LetDeclaration, VarDeclaration, TypeDeclaration,
  StoreDeclaration, EmbedDeclaration, NodeDeclaration, BotDeclaration,
  CommandDeclaration, EventDeclaration, FnDeclaration, IfStatement,
  MatchStatement, ForInStatement, ForRangeStatement, WhileStatement,
  TryCatchStatement, ReturnStatement, ThrowStatement, EmitStatement,
  ReplyStatement, DmStatement, LogStatement, RoleStatement, ReactStatement,
  AssignStatement, ExpressionStatement, EveryStatement, AfterStatement,
  PaginateStatement, ModalStatement, SelectStatement, JsEscapeStatement,
  WaitStatement, BreakStatement, ContinueStatement,
  Identifier, Literal, TemplateLiteral, ArrayLiteral, MapLiteral,
  TypeInstantiation, BinaryExpression, UnaryExpression, TernaryExpression,
  NullCoalesce, IsExpression, MemberExpression, IndexExpression,
  CallExpression, ArrowFunction, ButtonNode, ButtonRowNode,
  ImportNode, ExportNode
} from "./types";
import { STDLIB } from "./stdlib";

export interface TranspileOptions {
  sourceComments?: boolean;
  minify?: boolean;
  target?: "commonjs" | "esm";
}

export class Transpiler {
  private indent = 0;
  private lines: string[] = [];
  private sourceMap: { nzsLine: number; jsLine: number }[] = [];
  private embedRegistry: Map<string, { properties: { key: string; value: ExpressionNode }[]; fields?: any[] }> = new Map();
  private storeNames: Set<string> = new Set();
  private commandHandlers: string[] = [];
  private eventHandlers: string[] = [];
  private buttonHandlers: Map<string, string[]> = new Map();
  private selectHandlers: Map<string, string[]> = new Map();
  private modalHandlers: Map<string, string[]> = new Map();
  private scheduledTasks: string[] = [];
  private options: TranspileOptions;
  private currentFile = "<input>";

  constructor(options: TranspileOptions = {}) {
    this.options = { sourceComments: true, minify: false, target: "commonjs", ...options };
  }

  transpile(program: ProgramNode, file = "<input>"): string {
    this.currentFile = file;
    this.lines = [];

    // Header
    this.emit(`// Generated by NizumoScript v1.0.0 — DO NOT EDIT`);
    this.emit(`// Source: ${file}`);
    this.emit(`"use strict";`);
    this.emit(``);

    // Discord.js import
    this.emit(`const { Client, GatewayIntentBits, EmbedBuilder, ActionRowBuilder,`);
    this.emit(`  ButtonBuilder, ButtonStyle, StringSelectMenuBuilder,`);
    this.emit(`  ModalBuilder, TextInputBuilder, TextInputStyle,`);
    this.emit(`  SlashCommandBuilder, REST, Routes, Events,`);
    this.emit(`  Collection, PermissionFlagsBits } = require("discord.js");`);
    this.emit(`require("dotenv").config();`);
    this.emit(``);

    // Stdlib
    this.emit(STDLIB);
    this.emit(``);

    // Process imports first
    for (const node of program.body) {
      if (node.kind === "Import") this.transpileImport(node as ImportNode);
    }

    // First pass: collect embeds and stores
    for (const node of program.body) {
      if (node.kind === "EmbedDeclaration") {
        const n = node as EmbedDeclaration;
        this.embedRegistry.set(n.name, { properties: n.properties, fields: n.fields });
      }
      if (node.kind === "StoreDeclaration") {
        this.storeNames.add((node as StoreDeclaration).name);
      }
      if (node.kind === "NodeDeclaration") {
        this.collectFromNode(node as NodeDeclaration);
      }
    }

    // Transpile all top-level nodes
    for (const node of program.body) {
      if (node.kind === "Import") continue; // already done
      this.transpileNode(node);
    }

    // Client setup and main
    this.emitClientSetup(program);

    return this.lines.join("\n");
  }

  private collectFromNode(node: NodeDeclaration) {
    for (const child of node.body) {
      if (child.kind === "EmbedDeclaration") {
        const n = child as EmbedDeclaration;
        this.embedRegistry.set(n.name, { properties: n.properties, fields: n.fields });
      }
      if (child.kind === "StoreDeclaration") {
        this.storeNames.add((child as StoreDeclaration).name);
      }
    }
  }

  // ─── Emit Helpers ──────────────────────────────────────────────────────────

  private emit(line: string) {
    const ind = this.options.minify ? "" : "  ".repeat(this.indent);
    this.lines.push(ind + line);
  }

  private emitBlank() { if (!this.options.minify) this.lines.push(""); }

  private comment(nzsLine: number, label: string) {
    if (this.options.sourceComments && !this.options.minify) {
      this.emit(`// [NZS:${nzsLine}] ${label}`);
    }
  }

  private ind(fn: () => void) {
    this.indent++;
    fn();
    this.indent--;
  }

  // ─── Imports ───────────────────────────────────────────────────────────────

  private transpileImport(node: ImportNode) {
    const p = node.path.endsWith(".nzs") ? node.path.replace(".nzs", ".js") : node.path;
    if (node.named.length > 0) {
      this.emit(`const { ${node.named.join(", ")} } = require("${p}");`);
    } else {
      this.emit(`require("${p}");`);
    }
  }

  // ─── Top-Level Dispatch ────────────────────────────────────────────────────

  private transpileNode(node: ASTNode) {
    switch (node.kind) {
      case "ConstDeclaration":    this.transpileConst(node as ConstDeclaration); break;
      case "LetDeclaration":      this.transpileLet(node as LetDeclaration); break;
      case "VarDeclaration":      this.transpileVar(node as VarDeclaration); break;
      case "TypeDeclaration":     this.transpileType(node as TypeDeclaration); break;
      case "StoreDeclaration":    this.transpileStore(node as StoreDeclaration); break;
      case "EmbedDeclaration":    this.transpileEmbed(node as EmbedDeclaration); break;
      case "NodeDeclaration":     this.transpileNodeDecl(node as NodeDeclaration); break;
      case "BotDeclaration":      break; // handled in emitClientSetup
      case "CommandDeclaration":  this.transpileCommand(node as CommandDeclaration); break;
      case "EventDeclaration":    this.transpileEvent(node as EventDeclaration); break;
      case "FnDeclaration":       this.transpileFn(node as FnDeclaration); break;
      case "EveryStatement":      this.transpileEvery(node as EveryStatement); break;
      case "AfterStatement":      this.transpileAfter(node as AfterStatement); break;
      case "Export":              this.transpileExport(node as ExportNode); break;
      case "JsEscapeStatement":   this.emit((node as JsEscapeStatement).code); break;
      // Statements inside blocks
      default:                    this.transpileStatement(node); break;
    }
  }

  // ─── Variables ─────────────────────────────────────────────────────────────

  private transpileConst(node: ConstDeclaration) {
    this.comment(node.line, `const ${node.name}`);
    this.emit(`const ${node.name} = ${this.transpileExpr(node.value)};`);
  }

  private transpileLet(node: LetDeclaration) {
    this.comment(node.line, `let ${node.name}`);
    this.emit(`let ${node.name} = ${this.transpileExpr(node.value)};`);
  }

  private transpileVar(node: VarDeclaration) {
    this.comment(node.line, `var ${this.typeStr(node.varType)} ${node.name}`);
    this.emit(`let ${node.name} = ${this.transpileExpr(node.value)};`);
  }

  // ─── Types ─────────────────────────────────────────────────────────────────

  private transpileType(node: TypeDeclaration) {
    this.comment(node.line, `type ${node.name}`);
    this.emit(`class ${node.name}${node.extends ? ` extends ${node.extends}` : ""} {`);
    this.ind(() => {
      this.emit(`constructor(fields = {}) {`);
      this.ind(() => {
        if (node.extends) this.emit(`super(fields);`);
        for (const f of node.fields) {
          const def = f.defaultValue ? this.transpileExpr(f.defaultValue) : this.defaultForType(f.type);
          this.emit(`this.${f.name} = fields.${f.name} !== undefined ? fields.${f.name} : ${def};`);
        }
      });
      this.emit(`}`);
    });
    this.emit(`}`);
    this.emitBlank();
  }

  private defaultForType(type: NZSType): string {
    if (type === "int" || type === "float") return "0";
    if (type === "str") return '""';
    if (type === "bool") return "false";
    if (type === "null" || typeof type === "object" && "nullable" in type) return "null";
    if (typeof type === "object" && "array" in type) return "[]";
    if (typeof type === "object" && "map" in type) return "{}";
    return "null";
  }

  private typeStr(type: NZSType): string {
    if (typeof type === "string") return type;
    if ("array" in type) return `${this.typeStr(type.array)}[]`;
    if ("map" in type) return `map<${this.typeStr(type.map.key)}, ${this.typeStr(type.map.value)}>`;
    if ("nullable" in type) return `${this.typeStr(type.nullable)}?`;
    if ("custom" in type) return type.custom;
    return "any";
  }

  // ─── Store ─────────────────────────────────────────────────────────────────

  private transpileStore(node: StoreDeclaration) {
    this.comment(node.line, `store ${node.name} (${node.scope})`);
    const defaults: string[] = [];
    for (const f of node.fields) {
      const def = f.defaultValue ? this.transpileExpr(f.defaultValue) : this.defaultForType(f.type);
      defaults.push(`${f.name}: ${def}`);
    }
    this.emit(`const ${node.name} = __createStore("${node.name}", "${node.scope}", {${defaults.join(", ")}});`);
    this.emitBlank();
  }

  // ─── Embed ─────────────────────────────────────────────────────────────────

  private transpileEmbed(node: EmbedDeclaration) {
    this.comment(node.line, `embed ${node.name}`);
    const props = this.embedPropsToObject(node.properties, node.fields);
    if (node.extends) {
      this.emit(`const __embed_${node.name}_base = { ...__embed_${node.extends}_base, ${props} };`);
    } else {
      this.emit(`const __embed_${node.name}_base = { ${props} };`);
    }
    this.emitBlank();
  }

  private embedPropsToObject(
    props: { key: string; value: ExpressionNode }[],
    fields?: { name: string; value: ExpressionNode; inline?: boolean }[]
  ): string {
    const parts = props.map(p => `${p.key}: ${this.transpileExpr(p.value)}`);
    if (fields && fields.length > 0) {
      const fieldParts = fields.map(f =>
        `{ name: ${JSON.stringify(f.name)}, value: ${this.transpileExpr(f.value)}${f.inline ? ", inline: true" : ""} }`
      );
      parts.push(`fields: [${fieldParts.join(", ")}]`);
    }
    return parts.join(", ");
  }

  private buildEmbedJS(node: ReplyStatement): string {
    if (node.embedName) {
      const overrides = node.overrides ? node.overrides.map(o => `${o.key}: ${this.transpileExpr(o.value)}`).join(", ") : "";
      const extraFields = node.fields ? `[${node.fields.map(f => `{ name: ${JSON.stringify(f.name)}, value: ${this.transpileExpr(f.value)} }`).join(", ")}]` : "[]";
      if (overrides || node.fields) {
        return `__buildEmbed(__embed_${node.embedName}_base, {${overrides}}, ${extraFields})`;
      }
      return `__embed_${node.embedName}_base`;
    }
    if (node.inlineEmbed) {
      const props = this.embedPropsToObject(node.inlineEmbed.properties, node.inlineEmbed.fields);
      return `{ ${props} }`;
    }
    return "null";
  }

  // ─── Node (container) ──────────────────────────────────────────────────────

  private transpileNodeDecl(node: NodeDeclaration) {
    this.comment(node.line, `node ${node.name}`);
    for (const child of node.body) {
      this.transpileNode(child);
    }
  }

  // ─── Bot Declaration ───────────────────────────────────────────────────────

  private getBotField(program: ProgramNode, key: string): ExpressionNode | undefined {
    for (const node of program.body) {
      if (node.kind === "BotDeclaration") {
        const f = (node as BotDeclaration).fields.find(f => f.key === key);
        if (f) return f.value;
      }
      if (node.kind === "NodeDeclaration") {
        for (const child of (node as NodeDeclaration).body) {
          if (child.kind === "BotDeclaration") {
            const f = (child as BotDeclaration).fields.find(f => f.key === key);
            if (f) return f.value;
          }
        }
      }
    }
    return undefined;
  }

  // ─── Commands ──────────────────────────────────────────────────────────────

  private transpileCommand(node: CommandDeclaration) {
    this.comment(node.line, `command ${node.name}`);
    const fnName = `__cmd_${node.name}`;
    this.commandHandlers.push(node.name);

    const prefixOpt = node.options.find(o => o.key === "prefix");
    const slashOpt = node.options.find(o => o.key === "slash");
    const permOpt = node.options.find(o => o.key === "permission");
    const cooldownOpt = node.options.find(o => o.key === "cooldown");
    const descOpt = node.options.find(o => o.key === "description");
    const aliasOpt = node.options.find(o => o.key === "alias");
    const ephemeralOpt = node.options.find(o => o.key === "ephemeral");

    const isPrefix = !prefixOpt || this.transpileExpr(prefixOpt.value) !== "false";
    const isSlash = slashOpt && this.transpileExpr(slashOpt.value) !== "false";
    const permission = permOpt ? this.transpileExpr(permOpt.value) : '"@everyone"';
    const cooldown = cooldownOpt ? this.transpileExpr(cooldownOpt.value) : "null";

    // Main handler function
    this.emit(`async function ${fnName}(ctx) {`);
    this.ind(() => {
      // Permission check
      if (permOpt) {
        this.emit(`if (!await __checkPermission(ctx, ${permission})) {`);
        this.ind(() => {
          this.emit(`await ctx.reply({ content: "You don't have permission to use this command.", ephemeral: true });`);
          this.emit(`return;`);
        });
        this.emit(`}`);
      }

      // Cooldown check
      if (cooldownOpt) {
        this.emit(`const __cd_${node.name} = __checkCooldown(ctx.user.id, "${node.name}", __durationToMs(${cooldown}));`);
        this.emit(`if (!__cd_${node.name}.ok) {`);
        this.ind(() => {
          this.emit(`await ctx.reply({ content: \`You're on cooldown! Wait \${__cd_${node.name}.remaining}s.\`, ephemeral: true });`);
          this.emit(`return;`);
        });
        this.emit(`}`);
      }

      // Extract params from ctx
      for (const p of node.params) {
        this.emit(`const ${p.name} = ctx.options?.${p.type === "mention" ? "getUser" : `get${p.type.charAt(0).toUpperCase() + p.type.slice(1)}`}?.("${p.name}") ?? ${p.defaultValue ? this.transpileExpr(p.defaultValue) : "null"};`);
      }

      // Body
      this.transpileBody(node.body);
    });
    this.emit(`}`);
    this.emitBlank();

    // Register button handlers found in this command
    this.extractButtonHandlers(node.body);
    this.extractSelectHandlers(node.body);
    this.extractModalHandlers(node.body);
  }

  private extractButtonHandlers(body: ASTNode[]) {
    for (const node of body) {
      if (node.kind === "ReplyStatement") {
        const r = node as ReplyStatement;
        if (r.button && r.button.id) {
          const id = this.transpileExpr(r.button.id).replace(/['"]/g, "");
          const lines: string[] = [];
          for (const s of r.button.onClick) {
            lines.push(this.transpileStatementToString(s));
          }
          this.buttonHandlers.set(id, lines);
        }
        if (r.buttons) {
          for (const row of r.buttons) {
            for (const btn of row.buttons) {
              if (btn.id && btn.onClick.length > 0) {
                const id = this.transpileExpr(btn.id).replace(/['"]/g, "");
                const lines: string[] = [];
                for (const s of btn.onClick) {
                  lines.push(this.transpileStatementToString(s));
                }
                this.buttonHandlers.set(id, lines);
              }
            }
          }
        }
      }
    }
  }

  private extractSelectHandlers(body: ASTNode[]) {
    for (const node of body) {
      if (node.kind === "SelectStatement") {
        const s = node as SelectStatement;
        const id = this.transpileExpr(s.id).replace(/['"]/g, "");
        const lines: string[] = [];
        for (const stmt of s.onSelectBody) {
          lines.push(this.transpileStatementToString(stmt));
        }
        this.selectHandlers.set(id, lines);
      }
    }
  }

  private extractModalHandlers(body: ASTNode[]) {
    for (const node of body) {
      if (node.kind === "ModalStatement") {
        const m = node as ModalStatement;
        const id = this.transpileExpr(m.id).replace(/['"]/g, "");
        const lines: string[] = [];
        for (const stmt of m.onSubmitBody) {
          lines.push(this.transpileStatementToString(stmt));
        }
        this.modalHandlers.set(id, lines);
      }
    }
  }

  // ─── Events ────────────────────────────────────────────────────────────────

  private transpileEvent(node: EventDeclaration) {
    this.comment(node.line, `event ${node.name}`);
    const fnName = `__event_${node.name}`;
    this.eventHandlers.push(node.name);

    this.emit(`async function ${fnName}(${node.params.join(", ")}) {`);
    this.ind(() => {
      this.transpileBody(node.body);
    });
    this.emit(`}`);
    this.emitBlank();
  }

  // ─── Functions ─────────────────────────────────────────────────────────────

  private transpileFn(node: FnDeclaration) {
    this.comment(node.line, `fn ${node.name}`);
    const mod = node.isExport ? "module.exports." : "";
    const asyncKw = node.isAsync ? "async " : "";
    const params = node.params.map(p => {
      if (p.defaultValue) return `${p.name} = ${this.transpileExpr(p.defaultValue)}`;
      return p.name;
    }).join(", ");

    if (node.isExport) {
      this.emit(`${asyncKw}function ${node.name}(${params}) {`);
    } else {
      this.emit(`${node.isPrivate ? "" : ""}${asyncKw}function ${node.name}(${params}) {`);
    }
    this.ind(() => {
      this.transpileBody(node.body);
    });
    this.emit(`}`);
    if (node.isExport) {
      this.emit(`module.exports.${node.name} = ${node.name};`);
    }
    this.emitBlank();
  }

  // ─── Export ────────────────────────────────────────────────────────────────

  private transpileExport(node: ExportNode) {
    if (node.declaration.kind === "FnDeclaration") {
      const fn = node.declaration as FnDeclaration;
      fn.isExport = true;
      this.transpileFn(fn);
    } else if (node.declaration.kind === "ConstDeclaration") {
      this.transpileConst(node.declaration as ConstDeclaration);
      this.emit(`module.exports.${(node.declaration as ConstDeclaration).name} = ${(node.declaration as ConstDeclaration).name};`);
    } else {
      this.transpileNode(node.declaration);
    }
  }

  // ─── Scheduled ─────────────────────────────────────────────────────────────

  private transpileEvery(node: EveryStatement) {
    this.comment(node.line, `every ${node.interval}`);
    const fnName = `__every_${this.scheduledTasks.length}`;
    this.scheduledTasks.push(`setInterval(${fnName}, __durationToMs("${node.interval}"));`);
    this.emit(`async function ${fnName}() {`);
    this.ind(() => this.transpileBody(node.body));
    this.emit(`}`);
    this.emitBlank();
  }

  private transpileAfter(node: AfterStatement) {
    this.comment(node.line, `after ${node.delay}`);
    const fnName = `__after_${this.scheduledTasks.length}`;
    this.scheduledTasks.push(`setTimeout(${fnName}, __durationToMs("${node.delay}"));`);
    this.emit(`async function ${fnName}() {`);
    this.ind(() => this.transpileBody(node.body));
    this.emit(`}`);
    this.emitBlank();
  }

  // ─── Statement Transpilation ───────────────────────────────────────────────

  private transpileBody(body: ASTNode[]) {
    for (const node of body) {
      this.transpileStatement(node);
    }
  }

  private transpileStatement(node: ASTNode) {
    switch (node.kind) {
      case "ConstDeclaration":    this.transpileConst(node as ConstDeclaration); break;
      case "LetDeclaration":      this.transpileLet(node as LetDeclaration); break;
      case "VarDeclaration":      this.transpileVar(node as VarDeclaration); break;
      case "FnDeclaration":       this.transpileFn(node as FnDeclaration); break;
      case "IfStatement":         this.transpileIf(node as IfStatement); break;
      case "MatchStatement":      this.transpileMatch(node as MatchStatement); break;
      case "ForInStatement":      this.transpileForIn(node as ForInStatement); break;
      case "ForRangeStatement":   this.transpileForRange(node as ForRangeStatement); break;
      case "WhileStatement":      this.transpileWhile(node as WhileStatement); break;
      case "TryCatchStatement":   this.transpileTryCatch(node as TryCatchStatement); break;
      case "ReturnStatement":     this.transpileReturn(node as ReturnStatement); break;
      case "BreakStatement":      this.emit(`break;`); break;
      case "ContinueStatement":   this.emit(`continue;`); break;
      case "ThrowStatement":      this.emit(`throw ${this.transpileExpr((node as ThrowStatement).value)};`); break;
      case "EmitStatement":       this.transpileEmit(node as EmitStatement); break;
      case "WaitStatement":       this.emit(`await wait(__durationToMs("${(node as WaitStatement).duration}"));`); break;
      case "ReplyStatement":      this.transpileReply(node as ReplyStatement); break;
      case "DmStatement":         this.transpileDm(node as DmStatement); break;
      case "LogStatement":        this.transpileLog(node as LogStatement); break;
      case "RoleStatement":       this.transpileRole(node as RoleStatement); break;
      case "ReactStatement":      this.emit(`await ctx.message?.react(${this.transpileExpr((node as ReactStatement).emoji)});`); break;
      case "PaginateStatement":   this.transpilePaginate(node as PaginateStatement); break;
      case "ModalStatement":      this.transpileModal(node as ModalStatement); break;
      case "SelectStatement":     this.transpileSelect(node as SelectStatement); break;
      case "AssignStatement":     this.transpileAssign(node as AssignStatement); break;
      case "ExpressionStatement": this.emit(`${this.transpileExpr((node as ExpressionStatement).expression)};`); break;
      case "EveryStatement":      this.transpileEvery(node as EveryStatement); break;
      case "AfterStatement":      this.transpileAfter(node as AfterStatement); break;
      case "JsEscapeStatement":   this.emit((node as JsEscapeStatement).code); break;
      default: break;
    }
  }

  // String version for collecting handlers
  private transpileStatementToString(node: ASTNode): string {
    const saved = this.lines;
    const savedIndent = this.indent;
    this.lines = [];
    this.indent = 0;
    this.transpileStatement(node);
    const result = this.lines.join("\n");
    this.lines = saved;
    this.indent = savedIndent;
    return result;
  }

  private transpileIf(node: IfStatement) {
    this.comment(node.line, "if");
    this.emit(`if (${this.transpileExpr(node.condition)}) {`);
    this.ind(() => this.transpileBody(node.consequent));
    this.emit(`}`);
    for (const alt of node.alternates) {
      this.emit(`else if (${this.transpileExpr(alt.condition)}) {`);
      this.ind(() => this.transpileBody(alt.body));
      this.emit(`}`);
    }
    if (node.else) {
      this.emit(`else {`);
      this.ind(() => this.transpileBody(node.else!));
      this.emit(`}`);
    }
  }

  private transpileMatch(node: MatchStatement) {
    this.comment(node.line, "match");
    this.emit(`switch (${this.transpileExpr(node.value)}) {`);
    this.ind(() => {
      for (const c of node.cases) {
        this.emit(`case ${this.transpileExpr(c.value)}: {`);
        this.ind(() => {
          this.transpileBody(c.body);
          this.emit(`break;`);
        });
        this.emit(`}`);
      }
      if (node.default) {
        this.emit(`default: {`);
        this.ind(() => {
          this.transpileBody(node.default!);
          this.emit(`break;`);
        });
        this.emit(`}`);
      }
    });
    this.emit(`}`);
  }

  private transpileForIn(node: ForInStatement) {
    this.comment(node.line, "for-in");
    if (node.index) {
      this.emit(`for (let ${node.index} = 0; ${node.index} < ${this.transpileExpr(node.iterable)}.length; ${node.index}++) {`);
      this.ind(() => {
        this.emit(`const ${node.item} = ${this.transpileExpr(node.iterable)}[${node.index}];`);
        this.transpileBody(node.body);
      });
      this.emit(`}`);
    } else {
      this.emit(`for (const ${node.item} of ${this.transpileExpr(node.iterable)}) {`);
      this.ind(() => this.transpileBody(node.body));
      this.emit(`}`);
    }
  }

  private transpileForRange(node: ForRangeStatement) {
    this.comment(node.line, "for-range");
    const from = this.transpileExpr(node.from);
    const to = this.transpileExpr(node.to);
    this.emit(`for (let ${node.variable} = ${from}; ${node.variable} <= ${to}; ${node.variable}++) {`);
    this.ind(() => this.transpileBody(node.body));
    this.emit(`}`);
  }

  private transpileWhile(node: WhileStatement) {
    this.comment(node.line, "while");
    this.emit(`while (${this.transpileExpr(node.condition)}) {`);
    this.ind(() => this.transpileBody(node.body));
    this.emit(`}`);
  }

  private transpileTryCatch(node: TryCatchStatement) {
    this.emit(`try {`);
    this.ind(() => this.transpileBody(node.body));
    this.emit(`}`);
    for (const c of node.catches) {
      this.emit(`catch (${c.param}) {`);
      this.ind(() => this.transpileBody(c.body));
      this.emit(`}`);
    }
    if (node.finally) {
      this.emit(`finally {`);
      this.ind(() => this.transpileBody(node.finally!));
      this.emit(`}`);
    }
  }

  private transpileReturn(node: ReturnStatement) {
    if (node.value) {
      this.emit(`return ${this.transpileExpr(node.value)};`);
    } else {
      this.emit(`return;`);
    }
  }

  private transpileEmit(node: EmitStatement) {
    const args = node.args.map(a => this.transpileExpr(a)).join(", ");
    this.emit(`client.emit("${node.event}"${args ? ", " + args : ""});`);
  }

  private transpileReply(node: ReplyStatement) {
    this.comment(node.line, "reply");
    const opts: string[] = [];

    if (node.message) {
      opts.push(`content: ${this.transpileExpr(node.message)}`);
    }

    if (node.embedName || node.inlineEmbed) {
      const embedJS = this.buildEmbedJS(node);
      opts.push(`embeds: [(() => { const __e = ${embedJS}; const b = new EmbedBuilder(); if (__e.title) b.setTitle(__e.title); if (__e.description) b.setDescription(__e.description); if (__e.color) b.setColor(__e.color); if (__e.thumbnail) b.setThumbnail(__e.thumbnail); if (__e.image) b.setImage(__e.image); if (__e.footer) b.setFooter({ text: __e.footer }); if (__e.author) b.setAuthor({ name: __e.author }); if (__e.fields) b.addFields(__e.fields); return b; })()]`);
    }

    if (node.ephemeral) opts.push(`ephemeral: true`);

    // Button
    if (node.button) {
      const btn = node.button;
      const styleMap: Record<string, string> = {
        primary: "ButtonStyle.Primary",
        secondary: "ButtonStyle.Secondary",
        success: "ButtonStyle.Success",
        danger: "ButtonStyle.Danger",
        link: "ButtonStyle.Link",
      };
      const style = styleMap[btn.style] || "ButtonStyle.Secondary";
      const btnId = btn.id ? this.transpileExpr(btn.id) : `"__btn_${Math.random().toString(36).slice(2)}"`;
      let btnJS = `new ButtonBuilder().setLabel(${this.transpileExpr(btn.label)}).setStyle(${style})`;
      if (btn.url) btnJS += `.setURL(${this.transpileExpr(btn.url)})`;
      else btnJS += `.setCustomId(${btnId})`;
      if (btn.disabled) btnJS += `.setDisabled(${this.transpileExpr(btn.disabled)})`;
      opts.push(`components: [new ActionRowBuilder().addComponents(${btnJS})]`);
    }

    // Multi-row buttons
    if (node.buttons && node.buttons.length > 0) {
      const rowsJS = node.buttons.map(row => {
        const btnsJS = row.buttons.map(btn => {
          const styleMap: Record<string, string> = {
            primary: "ButtonStyle.Primary",
            secondary: "ButtonStyle.Secondary",
            success: "ButtonStyle.Success",
            danger: "ButtonStyle.Danger",
            link: "ButtonStyle.Link",
          };
          const style = styleMap[btn.style] || "ButtonStyle.Secondary";
          const btnId = btn.id ? this.transpileExpr(btn.id) : `"__btn_${Math.random().toString(36).slice(2)}"`;
          let b = `new ButtonBuilder().setLabel(${this.transpileExpr(btn.label)}).setStyle(${style})`;
          if (btn.url) b += `.setURL(${this.transpileExpr(btn.url)})`;
          else b += `.setCustomId(${btnId})`;
          if (btn.disabled) b += `.setDisabled(${this.transpileExpr(btn.disabled)})`;
          return b;
        });
        return `new ActionRowBuilder().addComponents(${btnsJS.join(", ")})`;
      });
      opts.push(`components: [${rowsJS.join(", ")}]`);
    }

    this.emit(`await ctx.reply({ ${opts.join(", ")} });`);
  }

  private transpileDm(node: DmStatement) {
    this.comment(node.line, "dm");
    if (node.embed) {
      const props = node.embed.properties.map(p => `${p.key}: ${this.transpileExpr(p.value)}`).join(", ");
      this.emit(`await (await ${this.transpileExpr(node.target)}.createDM()).send({ embeds: [(() => { const __e = {${props}}; const b = new EmbedBuilder(); if (__e.title) b.setTitle(__e.title); if (__e.description) b.setDescription(__e.description); if (__e.color) b.setColor(__e.color); return b; })()] });`);
    } else if (node.message) {
      this.emit(`await (await ${this.transpileExpr(node.target)}.createDM()).send({ content: ${this.transpileExpr(node.message)} });`);
    }
  }

  private transpileLog(node: LogStatement) {
    if (node.level === "log") this.emit(`log(${this.transpileExpr(node.value)});`);
    else if (node.level === "warn") this.emit(`log.warn(${this.transpileExpr(node.value)});`);
    else this.emit(`log.error(${this.transpileExpr(node.value)});`);
  }

  private transpileRole(node: RoleStatement) {
    const member = this.transpileExpr(node.member);
    const role = this.transpileExpr(node.role);
    if (node.action === "give") {
      this.emit(`await ${member}.roles.add(${role});`);
    } else if (node.action === "remove") {
      this.emit(`await ${member}.roles.remove(${role});`);
    } else if (node.action === "has") {
      this.emit(`${member}.roles.cache.has(${role})`);
    }
  }

  private transpilePaginate(node: PaginateStatement) {
    this.comment(node.line, "paginate");
    const pages = node.pages.map(p => {
      const props = p.properties.map(pr => `${pr.key}: ${this.transpileExpr(pr.value)}`).join(", ");
      return `{ ${props} }`;
    });
    const timeout = node.timeout ? `__durationToMs("${node.timeout}")` : "60000";
    this.emit(`await __paginate(ctx, [${pages.join(", ")}], ${timeout});`);
  }

  private transpileModal(node: ModalStatement) {
    this.comment(node.line, "modal");
    this.emit(`{`);
    this.ind(() => {
      this.emit(`const __modal = new ModalBuilder()`);
      this.emit(`  .setTitle(${this.transpileExpr(node.title)})`);
      this.emit(`  .setCustomId(${this.transpileExpr(node.id)});`);
      this.emit(`const __rows = [];`);
      for (const input of node.inputs) {
        this.emit(`{`);
        this.ind(() => {
          this.emit(`const __input = new TextInputBuilder()`);
          this.emit(`  .setCustomId(${this.transpileExpr(input.id)})`);
          this.emit(`  .setLabel(${this.transpileExpr(input.label)})`);
          this.emit(`  .setStyle(TextInputStyle.Short)`);
          if (input.placeholder) this.emit(`  .setPlaceholder(${this.transpileExpr(input.placeholder)})`);
          this.emit(`  .setRequired(${input.required ? "true" : "false"});`);
          this.emit(`__rows.push(new ActionRowBuilder().addComponents(__input));`);
        });
        this.emit(`}`);
      }
      this.emit(`__modal.addComponents(...__rows);`);
      this.emit(`await ctx.showModal(__modal);`);
    });
    this.emit(`}`);
  }

  private transpileSelect(node: SelectStatement) {
    this.comment(node.line, "select");
    this.emit(`{`);
    this.ind(() => {
      this.emit(`const __select = new StringSelectMenuBuilder()`);
      this.emit(`  .setCustomId(${this.transpileExpr(node.id)})`);
      if (node.placeholder) this.emit(`  .setPlaceholder(${this.transpileExpr(node.placeholder)})`);
      this.emit(`  .addOptions(`);
      this.ind(() => {
        for (const opt of node.options) {
          this.emit(`{ label: ${this.transpileExpr(opt.label)}, value: ${this.transpileExpr(opt.value)}${opt.description ? `, description: ${this.transpileExpr(opt.description)}` : ""} },`);
        }
      });
      this.emit(`  );`);
      this.emit(`const __row = new ActionRowBuilder().addComponents(__select);`);
      this.emit(`await ctx.reply({ components: [__row] });`);
    });
    this.emit(`}`);
  }

  private transpileAssign(node: AssignStatement) {
    this.emit(`${this.transpileExpr(node.target)} ${node.operator} ${this.transpileExpr(node.value)};`);
  }

  // ─── Expression Transpilation ──────────────────────────────────────────────

  transpileExpr(expr: ExpressionNode): string {
    switch (expr.kind) {
      case "Literal":
        if (expr.value === null) return "null";
        if (typeof expr.value === "string") return JSON.stringify(expr.value);
        if (typeof expr.value === "boolean") return String(expr.value);
        return String(expr.value);

      case "Identifier":
        return expr.name.startsWith("@") ? JSON.stringify(expr.name) : expr.name;

      case "TemplateLiteral":
        return this.transpileTemplateLiteral(expr);

      case "ArrayLiteral":
        return `[${expr.elements.map(e => this.transpileExpr(e)).join(", ")}]`;

      case "MapLiteral":
        return `{ ${expr.entries.map(e => `[${this.transpileExpr(e.key)}]: ${this.transpileExpr(e.value)}`).join(", ")} }`;

      case "TypeInstantiation":
        return `new ${expr.typeName}({ ${expr.fields.map(f => `${f.key}: ${this.transpileExpr(f.value)}`).join(", ")} })`;

      case "BinaryExpression":
        return `(${this.transpileExpr(expr.left)} ${this.mapOperator(expr.operator)} ${this.transpileExpr(expr.right)})`;

      case "UnaryExpression":
        return `${expr.operator}${this.transpileExpr(expr.operand)}`;

      case "TernaryExpression":
        return `(${this.transpileExpr(expr.condition)} ? ${this.transpileExpr(expr.consequent)} : ${this.transpileExpr(expr.alternate)})`;

      case "NullCoalesce":
        return `(${this.transpileExpr(expr.left)} ?? ${this.transpileExpr(expr.right)})`;

      case "IsExpression": {
        const val = this.transpileExpr(expr.value);
        const check = this.generateIsCheck(val, expr.checkType);
        return expr.negated ? `!(${check})` : check;
      }

      case "MemberExpression":
        if (expr.optional) return `${this.transpileExpr(expr.object)}?.${expr.property}`;
        return `${this.transpileExpr(expr.object)}.${expr.property}`;

      case "IndexExpression":
        return `${this.transpileExpr(expr.object)}[${this.transpileExpr(expr.index)}]`;

      case "CallExpression": {
        const callee = this.transpileExpr(expr.callee);
        const args = expr.args.map(a => this.transpileExpr(a)).join(", ");
        const awaitKw = expr.await ? "await " : "";
        return `${awaitKw}${callee}(${args})`;
      }

      case "ArrowFunction": {
        const params = expr.params.map(p => p.name).join(", ");
        if (Array.isArray(expr.body)) {
          const saved = this.lines;
          const savedIndent = this.indent;
          this.lines = [];
          this.indent = 0;
          this.transpileBody(expr.body);
          const body = this.lines.join("\n");
          this.lines = saved;
          this.indent = savedIndent;
          return `async (${params}) => { ${body} }`;
        }
        return `(${params}) => ${this.transpileExpr(expr.body)}`;
      }

      default:
        return "undefined";
    }
  }

  private transpileTemplateLiteral(expr: TemplateLiteral): string {
    const parts = expr.parts.map(part => {
      if ("text" in part) {
        return part.text.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
      } else {
        const val = this.transpileExpr(part.expr);
        if (part.format) {
          return `\${__formatNumber(${val}, "${part.format}")}`;
        }
        return `\${${val}}`;
      }
    });
    return "`" + parts.join("") + "`";
  }

  private mapOperator(op: string): string {
    if (op === "==") return "===";
    if (op === "!=") return "!==";
    return op;
  }

  private generateIsCheck(val: string, type: string): string {
    switch (type) {
      case "int": return `Number.isInteger(${val})`;
      case "float": return `typeof ${val} === "number"`;
      case "str": return `typeof ${val} === "string"`;
      case "bool": return `typeof ${val} === "boolean"`;
      case "null": return `${val} === null`;
      case "any": return `true`;
      default: return `${val} instanceof ${type}`;
    }
  }

  // ─── Client Setup ──────────────────────────────────────────────────────────

  private emitClientSetup(program: ProgramNode) {
    this.emitBlank();
    this.comment(0, "Discord.js client setup");

    // Find bot block
    let botFields: { key: string; value: ExpressionNode }[] = [];
    for (const node of program.body) {
      if (node.kind === "BotDeclaration") {
        botFields = (node as BotDeclaration).fields;
      }
      if (node.kind === "NodeDeclaration") {
        for (const child of (node as NodeDeclaration).body) {
          if (child.kind === "BotDeclaration") {
            botFields = (child as BotDeclaration).fields;
          }
        }
      }
    }

    const tokenField = botFields.find(f => f.key === "token");
    const prefixField = botFields.find(f => f.key === "prefix");
    const statusField = botFields.find(f => f.key === "status");
    const activityField = botFields.find(f => f.key === "activity");
    const activityTypeField = botFields.find(f => f.key === "activityType");
    const intentsField = botFields.find(f => f.key === "intents");

    const token = tokenField ? this.transpileExpr(tokenField.value) : "env.TOKEN";
    const prefix = prefixField ? this.transpileExpr(prefixField.value) : '"!"';

    this.emit(`const client = new Client({`);
    this.ind(() => {
      this.emit(`intents: [`);
      this.ind(() => {
        this.emit(`GatewayIntentBits.Guilds,`);
        this.emit(`GatewayIntentBits.GuildMessages,`);
        this.emit(`GatewayIntentBits.MessageContent,`);
        this.emit(`GatewayIntentBits.GuildMembers,`);
        this.emit(`GatewayIntentBits.GuildMessageReactions,`);
        this.emit(`GatewayIntentBits.DirectMessages,`);
      });
      this.emit(`],`);
    });
    this.emit(`});`);
    this.emitBlank();

    // Prefix commands
    if (this.commandHandlers.length > 0) {
      this.emit(`const __prefix = ${prefix};`);
      this.emitBlank();
    }

    // Slash command registration data
    const slashCommands = this.commandHandlers.filter(name => {
      for (const node of program.body) {
        if (node.kind === "CommandDeclaration" && (node as CommandDeclaration).name === name) {
          return (node as CommandDeclaration).options.find(o => o.key === "slash");
        }
      }
      return false;
    });

    // Ready event
    this.emit(`client.once(Events.ClientReady, async (c) => {`);
    this.ind(() => {
      this.emit(`console.log(\`[NZS] Logged in as \${c.user.tag}\`);`);

      if (statusField) {
        const status = this.transpileExpr(statusField.value);
        const actType = activityTypeField ? this.transpileExpr(activityTypeField.value) : '"playing"';
        const actName = activityField ? this.transpileExpr(activityField.value) : '""';
        this.emit(`c.user.setPresence({ activities: [{ name: ${actName}, type: { playing: 0, watching: 3, listening: 2, competing: 5 }[${actType}] ?? 0 }], status: ${status} });`);
      }

      // Register slash commands
      if (slashCommands.length > 0) {
        this.emit(`// Slash command registration`);
        this.emit(`const __cmds = [];`);
        for (const name of this.commandHandlers) {
          let cmd: CommandDeclaration | undefined;
          for (const node of program.body) {
            if (node.kind === "CommandDeclaration" && (node as CommandDeclaration).name === name) cmd = node as CommandDeclaration;
          }
          if (!cmd) continue;
          const descOpt = cmd.options.find(o => o.key === "description");
          const desc = descOpt ? this.transpileExpr(descOpt.value) : `"${name} command"`;
          this.emit(`__cmds.push(new SlashCommandBuilder().setName("${name}").setDescription(${desc}).toJSON());`);
        }
        this.emit(`try {`);
        this.ind(() => {
          this.emit(`const __rest = new REST().setToken(${token});`);
          this.emit(`if (process.env.GUILD_ID) {`);
          this.ind(() => {
            this.emit(`await __rest.put(Routes.applicationGuildCommands(c.user.id, process.env.GUILD_ID), { body: __cmds });`);
          });
          this.emit(`} else {`);
          this.ind(() => {
            this.emit(`await __rest.put(Routes.applicationCommands(c.user.id), { body: __cmds });`);
          });
          this.emit(`}`);
          this.emit(`console.log(\`[NZS] Registered \${__cmds.length} slash command(s)\`);`);
        });
        this.emit(`} catch (e) { console.error("[NZS] Slash registration failed:", e); }`);
      }

      // Scheduled tasks
      for (const task of this.scheduledTasks) {
        this.emit(task);
      }
    });
    this.emit(`});`);
    this.emitBlank();

    // Message event (prefix commands)
    if (this.commandHandlers.length > 0) {
      this.emit(`client.on(Events.MessageCreate, async (message) => {`);
      this.ind(() => {
        this.emit(`if (message.author.bot) return;`);
        this.emit(`if (!message.content.startsWith(__prefix)) return;`);
        this.emit(`const [__rawCmd, ...__args] = message.content.slice(__prefix.length).trim().split(/\\s+/);`);
        this.emit(`const __cmd = __rawCmd.toLowerCase();`);
        this.emit(`const ctx = { message, user: message.author, member: message.member, guild: message.guild, channel: message.channel, args: __args, options: null, reply: (opts) => message.reply(typeof opts === "string" ? { content: opts } : opts) };`);
        this.emitBlank();
        for (const name of this.commandHandlers) {
          // Check aliases
          let cmd: CommandDeclaration | undefined;
          for (const node of program.body) {
            if (node.kind === "CommandDeclaration" && (node as CommandDeclaration).name === name) cmd = node as CommandDeclaration;
          }
          const aliasOpt = cmd?.options.find(o => o.key === "alias");
          if (aliasOpt) {
            const aliases = this.transpileExpr(aliasOpt.value);
            this.emit(`if (__cmd === "${name}" || [${aliases}].includes(__cmd)) await __cmd_${name}(ctx);`);
          } else {
            this.emit(`if (__cmd === "${name}") await __cmd_${name}(ctx);`);
          }
        }
      });
      this.emit(`});`);
      this.emitBlank();
    }

    // Interaction event (slash commands + buttons + selects + modals)
    this.emit(`client.on(Events.InteractionCreate, async (interaction) => {`);
    this.ind(() => {
      // Slash
      if (this.commandHandlers.length > 0) {
        this.emit(`if (interaction.isChatInputCommand()) {`);
        this.ind(() => {
          this.emit(`const ctx = { user: interaction.user, member: interaction.member, guild: interaction.guild, channel: interaction.channel, options: interaction.options, reply: (opts) => interaction.reply(typeof opts === "string" ? { content: opts } : opts), showModal: (m) => interaction.showModal(m) };`);
          for (const name of this.commandHandlers) {
            this.emit(`if (interaction.commandName === "${name}") { await __cmd_${name}(ctx); return; }`);
          }
        });
        this.emit(`}`);
        this.emitBlank();
      }

      // Buttons
      if (this.buttonHandlers.size > 0) {
        this.emit(`if (interaction.isButton()) {`);
        this.ind(() => {
          this.emit(`const ctx = { user: interaction.user, member: interaction.member, guild: interaction.guild, channel: interaction.channel, interaction, reply: (opts) => interaction.reply(typeof opts === "string" ? { content: opts } : opts), update: (opts) => interaction.update(opts) };`);
          for (const [id, lines] of this.buttonHandlers) {
            this.emit(`if (interaction.customId === "${id}") {`);
            this.ind(() => { for (const l of lines) this.emit(l); });
            this.emit(`return;`);
            this.emit(`}`);
          }
        });
        this.emit(`}`);
        this.emitBlank();
      }

      // Selects
      if (this.selectHandlers.size > 0) {
        this.emit(`if (interaction.isStringSelectMenu()) {`);
        this.ind(() => {
          this.emit(`const ctx = { user: interaction.user, member: interaction.member, guild: interaction.guild, channel: interaction.channel, values: interaction.values, reply: (opts) => interaction.reply(typeof opts === "string" ? { content: opts } : opts) };`);
          for (const [id, lines] of this.selectHandlers) {
            this.emit(`if (interaction.customId === "${id}") {`);
            this.ind(() => { for (const l of lines) this.emit(l); });
            this.emit(`return;`);
            this.emit(`}`);
          }
        });
        this.emit(`}`);
      }

      // Modals
      if (this.modalHandlers.size > 0) {
        this.emit(`if (interaction.isModalSubmit()) {`);
        this.ind(() => {
          this.emit(`const ctx = { user: interaction.user, member: interaction.member, guild: interaction.guild, channel: interaction.channel, fields: interaction.fields, reply: (opts) => interaction.reply(typeof opts === "string" ? { content: opts } : opts) };`);
          for (const [id, lines] of this.modalHandlers) {
            this.emit(`if (interaction.customId === "${id}") {`);
            this.ind(() => { for (const l of lines) this.emit(l); });
            this.emit(`return;`);
            this.emit(`}`);
          }
        });
        this.emit(`}`);
      }

      // Pagination built-in buttons
      this.emit(`if (interaction.isButton() && (interaction.customId === "__page_prev" || interaction.customId === "__page_next")) return;`);
    });
    this.emit(`});`);
    this.emitBlank();

    // Custom events
    for (const name of this.eventHandlers) {
      const djsEventMap: Record<string, string> = {
        ready: "Events.ClientReady",
        message: "Events.MessageCreate",
        messageCreate: "Events.MessageCreate",
        guildMemberAdd: "Events.GuildMemberAdd",
        guildMemberRemove: "Events.GuildMemberRemove",
        guildCreate: "Events.GuildCreate",
        guildDelete: "Events.GuildDelete",
        reactionAdd: "Events.MessageReactionAdd",
        reactionRemove: "Events.MessageReactionRemove",
        interactionCreate: "Events.InteractionCreate",
        error: "Events.Error",
      };
      const djsEvent = djsEventMap[name] || `"${name}"`;
      this.emit(`client.on(${djsEvent}, __event_${name});`);
    }

    this.emitBlank();

    // Login
    this.emit(`// Start the bot`);
    this.emit(`client.login(${token}).catch(err => {`);
    this.ind(() => {
      this.emit(`console.error("[NZS] Login failed:", err.message);`);
      this.emit(`process.exit(1);`);
    });
    this.emit(`});`);
  }
}
